"""Add item_category to Inventory

Revision ID: 319f44c24bd7
Revises: 
Create Date: 2024-08-24 10:46:01.630231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319f44c24bd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_category', sa.Integer(), nullable=False))
        batch_op.alter_column('expire_date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'N/A'"))
        batch_op.create_foreign_key(None, 'categories', ['item_category'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('expire_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'N/A'"))
        batch_op.drop_column('item_category')


    # ### end Alembic commands ###
